name: CI/CD Pipeline

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Run Lint
        run: |
          npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Build project
        run: |
          npm run build-and-pack
