name: Check MR Title

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-mr:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Commitizen
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - name: Check PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"
          cz check --message "$PR_TITLE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
