name: Publish npm package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if MR title contains "bump"
        id: check_bump
        run: |
          if [[ "${{ github.event.pull_request.title }}" != *"bump"* ]]; then
            echo "Pull Request title does not contain 'bump'. Exiting..."
            exit 1
          else
            echo "Pull Request title contains 'bump'. Proceeding with publish."
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
